<?php

namespace Database\Seeders;

use App\Models\SeoMeta;
use Illuminate\Database\Seeder;

class SeoMetaSeeder extends Seeder
{
    public function run(): void
    {
        $seoData = [
            [
                'page_key' => 'home',
                'title' => 'ZendoIndia - Find Your Perfect Property | Real Estate in India',
                'description' => 'Discover premium residential and commercial properties across India. ZendoIndia offers verified listings, expert guidance, and seamless property buying experience.',
                'keywords' => 'real estate india, property for sale, buy property, residential property, commercial property, flats, apartments, villas, plots',
                'og_title' => 'ZendoIndia - Find Your Perfect Property',
                'og_description' => 'Discover premium residential and commercial properties across India with ZendoIndia.',
                'og_image' => null,
                'schema_markup' => json_encode([
                    '@context' => 'https://schema.org',
                    '@type' => 'RealEstateAgent',
                    'name' => 'ZendoIndia',
                    'description' => 'Premium real estate services in India',
                    'url' => config('app.url'),
                ], JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT),
                'faq_schema' => null,
            ],
            [
                'page_key' => 'about',
                'title' => 'About Us - ZendoIndia | Our Story & Mission',
                'description' => 'Learn about ZendoIndia, our mission to simplify property buying in India, our experienced team, and our commitment to transparency and customer satisfaction.',
                'keywords' => 'about zendoindia, real estate company, property consultants, our team, our mission',
                'og_title' => 'About ZendoIndia - Our Story & Mission',
                'og_description' => 'Learn about ZendoIndia and our mission to simplify property buying in India.',
                'og_image' => null,
                'schema_markup' => json_encode([
                    '@context' => 'https://schema.org',
                    '@type' => 'AboutPage',
                    'name' => 'About ZendoIndia',
                    'description' => 'Learn about ZendoIndia and our mission',
                ], JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT),
                'faq_schema' => null,
            ],
            [
                'page_key' => 'contact',
                'title' => 'Contact Us - ZendoIndia | Get in Touch',
                'description' => 'Contact ZendoIndia for property inquiries, site visits, and expert real estate consultation. Reach us via phone, email, or visit our office.',
                'keywords' => 'contact zendoindia, real estate inquiry, property consultation, office address, phone number',
                'og_title' => 'Contact ZendoIndia - Get in Touch',
                'og_description' => 'Contact ZendoIndia for property inquiries and expert real estate consultation.',
                'og_image' => null,
                'schema_markup' => json_encode([
                    '@context' => 'https://schema.org',
                    '@type' => 'ContactPage',
                    'name' => 'Contact ZendoIndia',
                    'description' => 'Get in touch with ZendoIndia for property inquiries',
                ], JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT),
                'faq_schema' => null,
            ],
            [
                'page_key' => 'properties',
                'title' => 'Properties for Sale - ZendoIndia | Browse All Listings',
                'description' => 'Browse verified properties for sale including flats, apartments, villas, plots, and commercial spaces. Filter by city, budget, BHK, and more.',
                'keywords' => 'properties for sale, buy flat, buy apartment, buy villa, buy plot, commercial property, property listings',
                'og_title' => 'Properties for Sale - ZendoIndia',
                'og_description' => 'Browse verified properties for sale including flats, apartments, villas, plots, and commercial spaces.',
                'og_image' => null,
                'schema_markup' => json_encode([
                    '@context' => 'https://schema.org',
                    '@type' => 'CollectionPage',
                    'name' => 'Properties for Sale',
                    'description' => 'Browse all property listings on ZendoIndia',
                ], JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT),
                'faq_schema' => null,
            ],
            [
                'page_key' => 'blogs',
                'title' => 'Real Estate Blog - ZendoIndia | Tips, News & Insights',
                'description' => 'Read the latest real estate news, property buying tips, market trends, and expert insights on the ZendoIndia blog.',
                'keywords' => 'real estate blog, property tips, market trends, buying guide, real estate news, investment tips',
                'og_title' => 'Real Estate Blog - ZendoIndia',
                'og_description' => 'Read the latest real estate news, property buying tips, and market trends.',
                'og_image' => null,
                'schema_markup' => json_encode([
                    '@context' => 'https://schema.org',
                    '@type' => 'Blog',
                    'name' => 'ZendoIndia Blog',
                    'description' => 'Real estate tips, news and insights',
                ], JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT),
                'faq_schema' => null,
            ],
            [
                'page_key' => 'privacy-policy',
                'title' => 'Privacy Policy - ZendoIndia',
                'description' => 'Read ZendoIndia privacy policy to understand how we collect, use, and protect your personal information.',
                'keywords' => 'privacy policy, data protection, personal information, cookies policy',
                'og_title' => 'Privacy Policy - ZendoIndia',
                'og_description' => 'Read ZendoIndia privacy policy to understand how we handle your data.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'terms-and-conditions',
                'title' => 'Terms & Conditions - ZendoIndia',
                'description' => 'Read ZendoIndia terms and conditions governing the use of our website and services.',
                'keywords' => 'terms and conditions, terms of service, user agreement, website terms',
                'og_title' => 'Terms & Conditions - ZendoIndia',
                'og_description' => 'Read ZendoIndia terms and conditions for using our services.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.acre-to-bigha',
                'title' => 'Acre to Bigha Converter - Free Online Calculator | ZendoIndia',
                'description' => 'Convert acres to bigha instantly with our free online calculator. Accurate land measurement conversion tool for Indian real estate.',
                'keywords' => 'acre to bigha, land conversion, area calculator, bigha converter, land measurement india',
                'og_title' => 'Acre to Bigha Converter - ZendoIndia',
                'og_description' => 'Convert acres to bigha instantly with our free online calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.acre-to-hectare',
                'title' => 'Acre to Hectare Converter - Free Online Calculator | ZendoIndia',
                'description' => 'Convert acres to hectares instantly with our free online calculator. Accurate land area conversion tool.',
                'keywords' => 'acre to hectare, land conversion, area calculator, hectare converter, land measurement',
                'og_title' => 'Acre to Hectare Converter - ZendoIndia',
                'og_description' => 'Convert acres to hectares instantly with our free online calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.emi-calculator',
                'title' => 'EMI Calculator - Home Loan EMI Calculator | ZendoIndia',
                'description' => 'Calculate your home loan EMI instantly. Free EMI calculator with detailed breakup of principal, interest, and total payment.',
                'keywords' => 'emi calculator, home loan emi, loan calculator, monthly installment, interest calculator, home loan',
                'og_title' => 'EMI Calculator - ZendoIndia',
                'og_description' => 'Calculate your home loan EMI instantly with our free calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.length-calculator',
                'title' => 'Length Converter - Free Online Calculator | ZendoIndia',
                'description' => 'Convert between different length units instantly. Free online length conversion calculator for feet, meters, inches, and more.',
                'keywords' => 'length converter, unit conversion, feet to meters, inches to cm, measurement calculator',
                'og_title' => 'Length Converter - ZendoIndia',
                'og_description' => 'Convert between different length units instantly with our free calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.acre-to-squaremeter',
                'title' => 'Acre to Square Meter Converter - Free Calculator | ZendoIndia',
                'description' => 'Convert acres to square meters instantly. Free online area conversion calculator for land measurement.',
                'keywords' => 'acre to square meter, area conversion, land calculator, sq meter converter',
                'og_title' => 'Acre to Square Meter Converter - ZendoIndia',
                'og_description' => 'Convert acres to square meters instantly with our free calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.cent-to-square-feet',
                'title' => 'Cent to Square Feet Converter - Free Calculator | ZendoIndia',
                'description' => 'Convert cents to square feet instantly. Free online land area conversion calculator.',
                'keywords' => 'cent to square feet, area conversion, land calculator, cent converter, sq feet',
                'og_title' => 'Cent to Square Feet Converter - ZendoIndia',
                'og_description' => 'Convert cents to square feet instantly with our free calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.cent-to-square-meter',
                'title' => 'Cent to Square Meter Converter - Free Calculator | ZendoIndia',
                'description' => 'Convert cents to square meters instantly. Free online land area conversion calculator.',
                'keywords' => 'cent to square meter, area conversion, land calculator, cent converter, sq meter',
                'og_title' => 'Cent to Square Meter Converter - ZendoIndia',
                'og_description' => 'Convert cents to square meters instantly with our free calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.cm-to-mm',
                'title' => 'CM to MM Converter - Free Online Calculator | ZendoIndia',
                'description' => 'Convert centimeters to millimeters instantly. Free online length conversion calculator.',
                'keywords' => 'cm to mm, centimeter to millimeter, length conversion, measurement calculator',
                'og_title' => 'CM to MM Converter - ZendoIndia',
                'og_description' => 'Convert centimeters to millimeters instantly with our free calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.cm-to-inches',
                'title' => 'CM to Inches Converter - Free Online Calculator | ZendoIndia',
                'description' => 'Convert centimeters to inches instantly. Free online length conversion calculator.',
                'keywords' => 'cm to inches, centimeter to inch, length conversion, measurement calculator',
                'og_title' => 'CM to Inches Converter - ZendoIndia',
                'og_description' => 'Convert centimeters to inches instantly with our free calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.ft-to-cm',
                'title' => 'Feet to CM Converter - Free Online Calculator | ZendoIndia',
                'description' => 'Convert feet to centimeters instantly. Free online length conversion calculator.',
                'keywords' => 'feet to cm, foot to centimeter, length conversion, measurement calculator',
                'og_title' => 'Feet to CM Converter - ZendoIndia',
                'og_description' => 'Convert feet to centimeters instantly with our free calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.ft-to-inches',
                'title' => 'Feet to Inches Converter - Free Online Calculator | ZendoIndia',
                'description' => 'Convert feet to inches instantly. Free online length conversion calculator.',
                'keywords' => 'feet to inches, foot to inch, length conversion, measurement calculator',
                'og_title' => 'Feet to Inches Converter - ZendoIndia',
                'og_description' => 'Convert feet to inches instantly with our free calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
            [
                'page_key' => 'calculators.ft-to-mm',
                'title' => 'Feet to MM Converter - Free Online Calculator | ZendoIndia',
                'description' => 'Convert feet to millimeters instantly. Free online length conversion calculator.',
                'keywords' => 'feet to mm, foot to millimeter, length conversion, measurement calculator',
                'og_title' => 'Feet to MM Converter - ZendoIndia',
                'og_description' => 'Convert feet to millimeters instantly with our free calculator.',
                'og_image' => null,
                'schema_markup' => null,
                'faq_schema' => null,
            ],
        ];

        foreach ($seoData as $data) {
            SeoMeta::updateOrCreate(
                ['page_key' => $data['page_key']],
                $data
            );
        }
    }
}
