<?php

return [
    'prefixes' => [
        'warehouse'                         => 'ZI-WH-',
        'apartment_flat_studio'            => 'ZI-RA-',
        'house_villa_farmhouse'            => 'ZI-RH-',
        'builder_floor'                    => 'ZI-RB-',
        'residential_plot_land'            => 'ZI-RP-',
        'service_apartment_pg'             => 'ZI-RS-',
        'office_space'                     => 'ZI-CO-',
        'retail_shop_showroom'             => 'ZI-CR-',
        'sez_eou_stpi_unit'                => 'ZI-CS-',
        'factory_manufacturing_industrial' => 'ZI-CF-',
        'commercial_institutional_land'    => 'ZI-CL-',
        'agricultural_farm_land'           => 'ZI-CA-',
        'multi_tenant_building'            => 'ZI-CB-',
        'hotel_resort_guesthouse_banquet'  => 'ZI-CH-',
    ],

    'types' => [
        'warehouse' => [
            'label'         => 'Warehouse / Cold Storage / Industrial Plot',
            'slug'          => 'warehouse',
            'property_type' => 'warehouse',
            'code_prefix'   => 'ZI-WH-',
            'group'         => 'warehousing',
            'route'         => 'owner.properties.create',
            'description'   => 'Warehousing facilities, logistics parks, cold storage & industrial plots',
        ],

        // Residential
        'apartment_flat_studio' => [
            'label'         => 'Apartment / Flat / Studio',
            'slug'          => 'apartment-flat-studio',
            'property_type' => 'apartment_flat_studio',
            'code_prefix'   => 'ZI-RA-',
            'group'         => 'residential',
            'description'   => 'High-rise apartments, flats, studio units & penthouses',
        ],
        'house_villa_farmhouse' => [
            'label'         => 'House / Villa / Farmhouse',
            'slug'          => 'house-villa-farmhouse',
            'property_type' => 'house_villa_farmhouse',
            'code_prefix'   => 'ZI-RH-',
            'group'         => 'residential',
            'description'   => 'Independent houses, luxury villas, bungalows & farmhouses',
        ],
        'builder_floor' => [
            'label'         => 'Builder Floor',
            'slug'          => 'builder-floor',
            'property_type' => 'builder_floor',
            'code_prefix'   => 'ZI-RB-',
            'group'         => 'residential',
            'description'   => 'Independent builder floor units & low-rise floors',
        ],
        'residential_plot_land' => [
            'label'         => 'Plot / Land',
            'slug'          => 'residential-plot-land',
            'property_type' => 'residential_plot_land',
            'code_prefix'   => 'ZI-RP-',
            'group'         => 'residential',
            'description'   => 'Residential plots, sub-divided land & development plots',
        ],
        'service_apartment_pg' => [
            'label'         => 'Service Apartment / Co-living / PG',
            'slug'          => 'service-apartment-pg',
            'property_type' => 'service_apartment_pg',
            'code_prefix'   => 'ZI-RS-',
            'group'         => 'residential',
            'description'   => 'Serviced residences, co-living spaces & Paying Guest accommodations',
        ],

        // Commercial
        'office_space' => [
            'label'         => 'Office Space',
            'slug'          => 'office-space',
            'property_type' => 'office_space',
            'code_prefix'   => 'ZI-CO-',
            'group'         => 'commercial',
            'description'   => 'Bare shell, warm shell & fully fitted office spaces',
        ],
        'retail_shop_showroom' => [
            'label'         => 'Shop / Showroom / Retail-Mall / Food Court',
            'slug'          => 'retail-shop-showroom',
            'property_type' => 'retail_shop_showroom',
            'code_prefix'   => 'ZI-CR-',
            'group'         => 'commercial',
            'description'   => 'Retail shops, high-street showrooms, mall units & food court spaces',
        ],
        'sez_eou_stpi_unit' => [
            'label'         => 'SEZ / EOU / STPI Unit',
            'slug'          => 'sez-eou-stpi-unit',
            'property_type' => 'sez_eou_stpi_unit',
            'code_prefix'   => 'ZI-CS-',
            'group'         => 'commercial',
            'description'   => 'Special Economic Zone, EOU & STPI IT park units',
        ],
        'factory_manufacturing_industrial' => [
            'label'         => 'Factory / Manufacturing / Industrial Building',
            'slug'          => 'factory-manufacturing-industrial',
            'property_type' => 'factory_manufacturing_industrial',
            'code_prefix'   => 'ZI-CF-',
            'group'         => 'commercial',
            'description'   => 'Manufacturing plants, industrial sheds, factories & processing units',
        ],
        'commercial_institutional_land' => [
            'label'         => 'Commercial / Institutional Land',
            'slug'          => 'commercial-institutional-land',
            'property_type' => 'commercial_institutional_land',
            'code_prefix'   => 'ZI-CL-',
            'group'         => 'commercial',
            'description'   => 'Commercial land, institutional plots & hospital/school land',
        ],
        'agricultural_farm_land' => [
            'label'         => 'Agricultural / Farm Land',
            'slug'          => 'agricultural-farm-land',
            'property_type' => 'agricultural_farm_land',
            'code_prefix'   => 'ZI-CA-',
            'group'         => 'commercial',
            'description'   => 'Agricultural land, farm plots, orchards & rural holdings',
        ],
        'multi_tenant_building' => [
            'label'         => 'Building / Multi-tenant',
            'slug'          => 'multi-tenant-building',
            'property_type' => 'multi_tenant_building',
            'code_prefix'   => 'ZI-CB-',
            'group'         => 'commercial',
            'description'   => 'Standalone commercial buildings & multi-tenant complexes',
        ],
        'hotel_resort_guesthouse_banquet' => [
            'label'         => 'Hotel / Resort / Guest House / Banquet',
            'slug'          => 'hotel-resort-guesthouse-banquet',
            'property_type' => 'hotel_resort_guesthouse_banquet',
            'code_prefix'   => 'ZI-CH-',
            'group'         => 'commercial',
            'description'   => 'Hotels, resorts, guest houses, wedding banquets & event venues',
        ],
    ],
];
